version: '3'
services:
  app:
    image: mcr.microsoft.com/java/jdk:17-zulu-alpine
    volumes:
      - .:/workspace:cached
    command: sleep infinity

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: topicos1
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: topicos1db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: