version: '3'
services:
  app:
    image: mcr.microsoft.com/java/jdk:17-zulu-alpine
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    networks:
      - mynetwork
    depends_on:
      - db
    ports:
      - "8080:8080"  # Mapeia a porta 8080 do host para a porta 8080 do contêiner

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: topicos1
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: topicos1db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  postgres-data:

networks:
  mynetwork:
    driver: bridge